// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mypro.proto

package com.sam.lib;

public interface GrpcStringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcStringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str = 1;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 1;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
