server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.255.129:3306/test?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
  redis:
    host: 192.168.255.129
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://sam:123456@192.168.255.129:27017/test

grpc:
  client:
    person:
      address: 'static://person:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext